name: DevHost - Terraform an Azure VM

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to Deploy'
        type: choice
        options:
          - 'tfstore'
          - 'network'
          - 'devhost'
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
          - 'plan'
          - 'apply'
          - 'destroy'

run-name: ${{ vars.ENV_NAME }} - Terraform ${{ github.event.inputs.component }} ${{ github.event.inputs.action }}

jobs:

  terraform-infra:

    runs-on: ubuntu-latest
    
    env:
      ENV_NAME: ${{ vars.ENV_NAME }}
      COMPONENT: ${{ github.event.inputs.component }}
      TERRAFORM_ACTION: ${{ github.event.inputs.action }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_TFSTORE_ACCESSKEY }}
      TFSTATE_SUFFIX: ${{ vars.TFSTATE_SUFFIX }}
      LOCATION: ${{ vars.LOCATION }}
      CIDR_BLOCK: ${{ vars.CIDR_BLOCK }}
      ADMIN_PASS: ${{ secrets.ADMIN_PASS }}

    steps:

      - name: Check Environment
        run: |
          echo "ENV_NAME: ${ENV_NAME}"
          echo "TERRAFORM_ACTION: ${TERRAFORM_ACTION}"
          echo "COMPONENT: $COMPONENT"
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"
          echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET"
          echo "TFSTATE_SUFFIX: ${TFSTATE_SUFFIX}"
          echo "LOCATION: ${LOCATION}"
          echo "CIDR_BLOCK: $CIDR_BLOCK"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Action
        env:
          ARM_SKIP_PROVIDER_REGISTRATION: true
        run: |
          cd azure
          echo "ENV_NAME: ${ENV_NAME}"
          ./terraform_runner.sh azure $COMPONENT $TERRAFORM_ACTION
